### ISSUE TITLE
Is there a way to use Appearance as a standalone tool?

### ISSUE THREAD

**Issue by jarisgv** [Martinomagnifico/reveal.js-appearance#8]
Hi @Martinomagnifico 

Congratulations for your plugin.

I wonder if there is a way to use Appearance as a standalone library to control Animate.css but doing things we can't achieve with other tools like Wow.js (which is also a great library) e.g. automatically animating child elements as UL and OL lists via JavaScript, saving a lot of coding time.

Thanks in advance

Jaris GV

**Comment by Martinomagnifico** [comment]
Hi Jaris, glad that you like Appearance! It is not standalone, but a plugin for Reveal.js specifically. You can simplify the assignment of animation classes through the options, with auto-appear. See https://github.com/Martinomagnifico/reveal.js-appearance#global-autoappear-mode . You can then let any specific tag or class appear with a single assignment. Hopefully that works for you!

**Comment by jarisgv** [comment]
Yeah, I'm using Appearance for a long while and have had great results e.g. creating social media videos saving a lot of time and stopping using Premiere and After Effects and still getting stunning animations.
But I use to animate my websites with other tools such as wow.js and gsap.js and Appearance really simplifies the things for me. That's why I ask you if there was a way to use it without turning the website's block into slides with 100vh.

Anyway, I'm really grateful for your plugin.
Thank you so much for your job.

⭐⭐⭐⭐⭐

**Comment by Martinomagnifico** [comment]
Then you’ll like the next version. 

In that version the user can use data-appearance=“words” on a sentence. It will then break that sentence apart into spans that inherit the animation class of the container-sentence. 

However, I’m still testing it, and looking at how delays work, because it will need an extra data-attribute (on the original sentence) for the first word, before it is broken into spans. 

I might call that “data-sentence-delay”. Still pondering the naming and how it should work.

**Comment by Martinomagnifico** [comment]
I’ll close the issue, because Appearance can’t easily be made stand-alone for use with websites.
